package com.czj.pojo;

import java.io.Serializable;

public class MyFriends implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.my_user_id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    private String myUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.my_friend_user_id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    private String myFriendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_friends
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.id
     *
     * @return the value of my_friends.id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.id
     *
     * @param id the value for my_friends.id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.my_user_id
     *
     * @return the value of my_friends.my_user_id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    public String getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.my_user_id
     *
     * @param myUserId the value for my_friends.my_user_id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    public void setMyUserId(String myUserId) {
        this.myUserId = myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.my_friend_user_id
     *
     * @return the value of my_friends.my_friend_user_id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    public String getMyFriendUserId() {
        return myFriendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.my_friend_user_id
     *
     * @param myFriendUserId the value for my_friends.my_friend_user_id
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    public void setMyFriendUserId(String myFriendUserId) {
        this.myFriendUserId = myFriendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Tue Jun 11 17:56:28 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", myUserId=").append(myUserId);
        sb.append(", myFriendUserId=").append(myFriendUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}