server:
  port: 8082
  context-path: /term


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


#mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.youbang
  config-locations: classpath:mybatis/mybatis-config.xml
  table:
    auto: update
  model:
    pack: com.youzhang.model
  database:
    type: mysql

#环境自定义参数
cookie:
  user_key: gnss_session_id
  company_key: gnss_com_key
  status_key: gnss_status

feign:
  hystrix:
    enabled: false

# 图片上传地址
upload:
  img-path: /data/web/driver/