package com.czj.dao;

import com.czj.pojo.ChatMsg;
import java.util.List;

public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Tue Jun 11 17:54:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Tue Jun 11 17:54:24 CST 2019
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Tue Jun 11 17:54:24 CST 2019
     */
    ChatMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Tue Jun 11 17:54:24 CST 2019
     */
    List<ChatMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Tue Jun 11 17:54:24 CST 2019
     */
    int updateByPrimaryKey(ChatMsg record);
}