package com.czj.dao;

import com.czj.pojo.ChatMsg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Jun 14 15:37:38 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Jun 14 15:37:38 CST 2019
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Jun 14 15:37:38 CST 2019
     */
    ChatMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Jun 14 15:37:38 CST 2019
     */
    List<ChatMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Jun 14 15:37:38 CST 2019
     */
    int updateByPrimaryKey(ChatMsg record);
}