package com.czj.dao;

import com.czj.pojo.FriendsRequest;
import java.util.List;

public interface FriendsRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Fri Jun 14 15:23:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Fri Jun 14 15:23:15 CST 2019
     */
    int insert(FriendsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Fri Jun 14 15:23:15 CST 2019
     */
    FriendsRequest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Fri Jun 14 15:23:15 CST 2019
     */
    List<FriendsRequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Fri Jun 14 15:23:15 CST 2019
     */
    int updateByPrimaryKey(FriendsRequest record);
}