package com.czj.bean;

import java.io.Serializable;

public class HDictionary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.status_color
     *
     * @mbg.generated
     */
    private String statusColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_dictionary.vehicle_licence
     *
     * @mbg.generated
     */
    private String vehicleLicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.id
     *
     * @return the value of h_dictionary.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.id
     *
     * @param id the value for h_dictionary.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.parent_id
     *
     * @return the value of h_dictionary.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.parent_id
     *
     * @param parentId the value for h_dictionary.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.name
     *
     * @return the value of h_dictionary.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.name
     *
     * @param name the value for h_dictionary.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.value
     *
     * @return the value of h_dictionary.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.value
     *
     * @param value the value for h_dictionary.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.sort
     *
     * @return the value of h_dictionary.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.sort
     *
     * @param sort the value for h_dictionary.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.status_color
     *
     * @return the value of h_dictionary.status_color
     *
     * @mbg.generated
     */
    public String getStatusColor() {
        return statusColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.status_color
     *
     * @param statusColor the value for h_dictionary.status_color
     *
     * @mbg.generated
     */
    public void setStatusColor(String statusColor) {
        this.statusColor = statusColor == null ? null : statusColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_dictionary.vehicle_licence
     *
     * @return the value of h_dictionary.vehicle_licence
     *
     * @mbg.generated
     */
    public String getVehicleLicence() {
        return vehicleLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_dictionary.vehicle_licence
     *
     * @param vehicleLicence the value for h_dictionary.vehicle_licence
     *
     * @mbg.generated
     */
    public void setVehicleLicence(String vehicleLicence) {
        this.vehicleLicence = vehicleLicence == null ? null : vehicleLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", name=").append(name);
        sb.append(", value=").append(value);
        sb.append(", sort=").append(sort);
        sb.append(", statusColor=").append(statusColor);
        sb.append(", vehicleLicence=").append(vehicleLicence);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}