package com.czj.bean;

import java.io.Serializable;

public class HExam implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.staff_id
     *
     * @mbg.generated
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.hiredate
     *
     * @mbg.generated
     */
    private String hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.kind_id
     *
     * @mbg.generated
     */
    private String kindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.examiner_id
     *
     * @mbg.generated
     */
    private String examinerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_exam.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.id
     *
     * @return the value of h_exam.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.id
     *
     * @param id the value for h_exam.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.staff_id
     *
     * @return the value of h_exam.staff_id
     *
     * @mbg.generated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.staff_id
     *
     * @param staffId the value for h_exam.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.create_time
     *
     * @return the value of h_exam.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.create_time
     *
     * @param createTime the value for h_exam.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.hiredate
     *
     * @return the value of h_exam.hiredate
     *
     * @mbg.generated
     */
    public String getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.hiredate
     *
     * @param hiredate the value for h_exam.hiredate
     *
     * @mbg.generated
     */
    public void setHiredate(String hiredate) {
        this.hiredate = hiredate == null ? null : hiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.kind_id
     *
     * @return the value of h_exam.kind_id
     *
     * @mbg.generated
     */
    public String getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.kind_id
     *
     * @param kindId the value for h_exam.kind_id
     *
     * @mbg.generated
     */
    public void setKindId(String kindId) {
        this.kindId = kindId == null ? null : kindId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.examiner_id
     *
     * @return the value of h_exam.examiner_id
     *
     * @mbg.generated
     */
    public String getExaminerId() {
        return examinerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.examiner_id
     *
     * @param examinerId the value for h_exam.examiner_id
     *
     * @mbg.generated
     */
    public void setExaminerId(String examinerId) {
        this.examinerId = examinerId == null ? null : examinerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_exam.result
     *
     * @return the value of h_exam.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_exam.result
     *
     * @param result the value for h_exam.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", staffId=").append(staffId);
        sb.append(", createTime=").append(createTime);
        sb.append(", hiredate=").append(hiredate);
        sb.append(", kindId=").append(kindId);
        sb.append(", examinerId=").append(examinerId);
        sb.append(", result=").append(result);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}