package com.czj.bean;

import java.io.Serializable;

public class HMoveInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.from_dept
     *
     * @mbg.generated
     */
    private String fromDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.to_dept
     *
     * @mbg.generated
     */
    private String toDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.creater_id
     *
     * @mbg.generated
     */
    private String createrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_move_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_move_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.id
     *
     * @return the value of h_move_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.id
     *
     * @param id the value for h_move_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.from_dept
     *
     * @return the value of h_move_info.from_dept
     *
     * @mbg.generated
     */
    public String getFromDept() {
        return fromDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.from_dept
     *
     * @param fromDept the value for h_move_info.from_dept
     *
     * @mbg.generated
     */
    public void setFromDept(String fromDept) {
        this.fromDept = fromDept == null ? null : fromDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.to_dept
     *
     * @return the value of h_move_info.to_dept
     *
     * @mbg.generated
     */
    public String getToDept() {
        return toDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.to_dept
     *
     * @param toDept the value for h_move_info.to_dept
     *
     * @mbg.generated
     */
    public void setToDept(String toDept) {
        this.toDept = toDept == null ? null : toDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.date
     *
     * @return the value of h_move_info.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.date
     *
     * @param date the value for h_move_info.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.desc
     *
     * @return the value of h_move_info.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.desc
     *
     * @param desc the value for h_move_info.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.creater_id
     *
     * @return the value of h_move_info.creater_id
     *
     * @mbg.generated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.creater_id
     *
     * @param createrId the value for h_move_info.creater_id
     *
     * @mbg.generated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.create_time
     *
     * @return the value of h_move_info.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.create_time
     *
     * @param createTime the value for h_move_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.type
     *
     * @return the value of h_move_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.type
     *
     * @param type the value for h_move_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_move_info.status
     *
     * @return the value of h_move_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_move_info.status
     *
     * @param status the value for h_move_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fromDept=").append(fromDept);
        sb.append(", toDept=").append(toDept);
        sb.append(", date=").append(date);
        sb.append(", desc=").append(desc);
        sb.append(", createrId=").append(createrId);
        sb.append(", createTime=").append(createTime);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}