package com.czj.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class HStaffLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.staff_id
     *
     * @mbg.generated
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.emp_num
     *
     * @mbg.generated
     */
    private String empNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.hiredate
     *
     * @mbg.generated
     */
    private String hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.dept_id
     *
     * @mbg.generated
     */
    private String deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.kind
     *
     * @mbg.generated
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.id_num
     *
     * @mbg.generated
     */
    private String idNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.work_type
     *
     * @mbg.generated
     */
    private String workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.hour_wage
     *
     * @mbg.generated
     */
    private BigDecimal hourWage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.month_wage
     *
     * @mbg.generated
     */
    private BigDecimal monthWage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.bank_card_num
     *
     * @mbg.generated
     */
    private String bankCardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.creater_id
     *
     * @mbg.generated
     */
    private String createrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.modify_time
     *
     * @mbg.generated
     */
    private String modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.fid
     *
     * @mbg.generated
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.operater_id
     *
     * @mbg.generated
     */
    private String operaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.operate_time
     *
     * @mbg.generated
     */
    private String operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.operate_type
     *
     * @mbg.generated
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_staff_log.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.id
     *
     * @return the value of h_staff_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.id
     *
     * @param id the value for h_staff_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.staff_id
     *
     * @return the value of h_staff_log.staff_id
     *
     * @mbg.generated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.staff_id
     *
     * @param staffId the value for h_staff_log.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.name
     *
     * @return the value of h_staff_log.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.name
     *
     * @param name the value for h_staff_log.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.gender
     *
     * @return the value of h_staff_log.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.gender
     *
     * @param gender the value for h_staff_log.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.birthday
     *
     * @return the value of h_staff_log.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.birthday
     *
     * @param birthday the value for h_staff_log.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.phone
     *
     * @return the value of h_staff_log.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.phone
     *
     * @param phone the value for h_staff_log.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.address
     *
     * @return the value of h_staff_log.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.address
     *
     * @param address the value for h_staff_log.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.emp_num
     *
     * @return the value of h_staff_log.emp_num
     *
     * @mbg.generated
     */
    public String getEmpNum() {
        return empNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.emp_num
     *
     * @param empNum the value for h_staff_log.emp_num
     *
     * @mbg.generated
     */
    public void setEmpNum(String empNum) {
        this.empNum = empNum == null ? null : empNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.hiredate
     *
     * @return the value of h_staff_log.hiredate
     *
     * @mbg.generated
     */
    public String getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.hiredate
     *
     * @param hiredate the value for h_staff_log.hiredate
     *
     * @mbg.generated
     */
    public void setHiredate(String hiredate) {
        this.hiredate = hiredate == null ? null : hiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.dept_id
     *
     * @return the value of h_staff_log.dept_id
     *
     * @mbg.generated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.dept_id
     *
     * @param deptId the value for h_staff_log.dept_id
     *
     * @mbg.generated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.job
     *
     * @return the value of h_staff_log.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.job
     *
     * @param job the value for h_staff_log.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.kind
     *
     * @return the value of h_staff_log.kind
     *
     * @mbg.generated
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.kind
     *
     * @param kind the value for h_staff_log.kind
     *
     * @mbg.generated
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.status
     *
     * @return the value of h_staff_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.status
     *
     * @param status the value for h_staff_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.id_num
     *
     * @return the value of h_staff_log.id_num
     *
     * @mbg.generated
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.id_num
     *
     * @param idNum the value for h_staff_log.id_num
     *
     * @mbg.generated
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.work_type
     *
     * @return the value of h_staff_log.work_type
     *
     * @mbg.generated
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.work_type
     *
     * @param workType the value for h_staff_log.work_type
     *
     * @mbg.generated
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.level
     *
     * @return the value of h_staff_log.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.level
     *
     * @param level the value for h_staff_log.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.hour_wage
     *
     * @return the value of h_staff_log.hour_wage
     *
     * @mbg.generated
     */
    public BigDecimal getHourWage() {
        return hourWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.hour_wage
     *
     * @param hourWage the value for h_staff_log.hour_wage
     *
     * @mbg.generated
     */
    public void setHourWage(BigDecimal hourWage) {
        this.hourWage = hourWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.month_wage
     *
     * @return the value of h_staff_log.month_wage
     *
     * @mbg.generated
     */
    public BigDecimal getMonthWage() {
        return monthWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.month_wage
     *
     * @param monthWage the value for h_staff_log.month_wage
     *
     * @mbg.generated
     */
    public void setMonthWage(BigDecimal monthWage) {
        this.monthWage = monthWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.bank
     *
     * @return the value of h_staff_log.bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.bank
     *
     * @param bank the value for h_staff_log.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.bank_card_num
     *
     * @return the value of h_staff_log.bank_card_num
     *
     * @mbg.generated
     */
    public String getBankCardNum() {
        return bankCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.bank_card_num
     *
     * @param bankCardNum the value for h_staff_log.bank_card_num
     *
     * @mbg.generated
     */
    public void setBankCardNum(String bankCardNum) {
        this.bankCardNum = bankCardNum == null ? null : bankCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.creater_id
     *
     * @return the value of h_staff_log.creater_id
     *
     * @mbg.generated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.creater_id
     *
     * @param createrId the value for h_staff_log.creater_id
     *
     * @mbg.generated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.modifier_id
     *
     * @return the value of h_staff_log.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.modifier_id
     *
     * @param modifierId the value for h_staff_log.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.create_time
     *
     * @return the value of h_staff_log.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.create_time
     *
     * @param createTime the value for h_staff_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.modify_time
     *
     * @return the value of h_staff_log.modify_time
     *
     * @mbg.generated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.modify_time
     *
     * @param modifyTime the value for h_staff_log.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.fid
     *
     * @return the value of h_staff_log.fid
     *
     * @mbg.generated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.fid
     *
     * @param fid the value for h_staff_log.fid
     *
     * @mbg.generated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.operater_id
     *
     * @return the value of h_staff_log.operater_id
     *
     * @mbg.generated
     */
    public String getOperaterId() {
        return operaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.operater_id
     *
     * @param operaterId the value for h_staff_log.operater_id
     *
     * @mbg.generated
     */
    public void setOperaterId(String operaterId) {
        this.operaterId = operaterId == null ? null : operaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.operate_time
     *
     * @return the value of h_staff_log.operate_time
     *
     * @mbg.generated
     */
    public String getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.operate_time
     *
     * @param operateTime the value for h_staff_log.operate_time
     *
     * @mbg.generated
     */
    public void setOperateTime(String operateTime) {
        this.operateTime = operateTime == null ? null : operateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.operate_type
     *
     * @return the value of h_staff_log.operate_type
     *
     * @mbg.generated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.operate_type
     *
     * @param operateType the value for h_staff_log.operate_type
     *
     * @mbg.generated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_staff_log.desc
     *
     * @return the value of h_staff_log.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_staff_log.desc
     *
     * @param desc the value for h_staff_log.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", staffId=").append(staffId);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", empNum=").append(empNum);
        sb.append(", hiredate=").append(hiredate);
        sb.append(", deptId=").append(deptId);
        sb.append(", job=").append(job);
        sb.append(", kind=").append(kind);
        sb.append(", status=").append(status);
        sb.append(", idNum=").append(idNum);
        sb.append(", workType=").append(workType);
        sb.append(", level=").append(level);
        sb.append(", hourWage=").append(hourWage);
        sb.append(", monthWage=").append(monthWage);
        sb.append(", bank=").append(bank);
        sb.append(", bankCardNum=").append(bankCardNum);
        sb.append(", createrId=").append(createrId);
        sb.append(", modifierId=").append(modifierId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", fid=").append(fid);
        sb.append(", operaterId=").append(operaterId);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", operateType=").append(operateType);
        sb.append(", desc=").append(desc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}