package com.czj.bean;

import java.io.Serializable;

public class HStoreForecastTurnover implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.store_id
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.total_money
     *
     * @mbg.generated
     */
    private Double totalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.time_money
     *
     * @mbg.generated
     */
    private String timeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.scheduling_date
     *
     * @mbg.generated
     */
    private String schedulingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_store_forecast_turnover.creater_id
     *
     * @mbg.generated
     */
    private String createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.id
     *
     * @return the value of h_store_forecast_turnover.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.id
     *
     * @param id the value for h_store_forecast_turnover.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.store_id
     *
     * @return the value of h_store_forecast_turnover.store_id
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.store_id
     *
     * @param storeId the value for h_store_forecast_turnover.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.total_money
     *
     * @return the value of h_store_forecast_turnover.total_money
     *
     * @mbg.generated
     */
    public Double getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.total_money
     *
     * @param totalMoney the value for h_store_forecast_turnover.total_money
     *
     * @mbg.generated
     */
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.time_money
     *
     * @return the value of h_store_forecast_turnover.time_money
     *
     * @mbg.generated
     */
    public String getTimeMoney() {
        return timeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.time_money
     *
     * @param timeMoney the value for h_store_forecast_turnover.time_money
     *
     * @mbg.generated
     */
    public void setTimeMoney(String timeMoney) {
        this.timeMoney = timeMoney == null ? null : timeMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.scheduling_date
     *
     * @return the value of h_store_forecast_turnover.scheduling_date
     *
     * @mbg.generated
     */
    public String getSchedulingDate() {
        return schedulingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.scheduling_date
     *
     * @param schedulingDate the value for h_store_forecast_turnover.scheduling_date
     *
     * @mbg.generated
     */
    public void setSchedulingDate(String schedulingDate) {
        this.schedulingDate = schedulingDate == null ? null : schedulingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.create_time
     *
     * @return the value of h_store_forecast_turnover.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.create_time
     *
     * @param createTime the value for h_store_forecast_turnover.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_store_forecast_turnover.creater_id
     *
     * @return the value of h_store_forecast_turnover.creater_id
     *
     * @mbg.generated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_store_forecast_turnover.creater_id
     *
     * @param createrId the value for h_store_forecast_turnover.creater_id
     *
     * @mbg.generated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeId=").append(storeId);
        sb.append(", totalMoney=").append(totalMoney);
        sb.append(", timeMoney=").append(timeMoney);
        sb.append(", schedulingDate=").append(schedulingDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", createrId=").append(createrId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}