server:
  port: 8081
  context-path: /mana


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


#mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.czj
  config-locations: classpath:mybatis/mybatis-config.xml
  table:
    auto: update
  model:
    pack: com.youzhang.model
  database:
    type: mysql

#环境自定义参数
cookie:
  user_key: d_SessionId
  company_key: d_com_key
  login_state_key: d_state

feign:
  hystrix:
    enabled: false