package com.czj.dao;

import com.czj.bean.HApplyMove;
import java.util.List;

public interface HApplyMoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_apply_move
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_apply_move
     *
     * @mbg.generated
     */
    int insert(HApplyMove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_apply_move
     *
     * @mbg.generated
     */
    HApplyMove selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_apply_move
     *
     * @mbg.generated
     */
    List<HApplyMove> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_apply_move
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HApplyMove record);
}