package com.czj.dao;

import com.czj.bean.HAuthorJobMenu;
import java.util.List;

public interface HAuthorJobMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_author_job_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_author_job_menu
     *
     * @mbg.generated
     */
    int insert(HAuthorJobMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_author_job_menu
     *
     * @mbg.generated
     */
    HAuthorJobMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_author_job_menu
     *
     * @mbg.generated
     */
    List<HAuthorJobMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_author_job_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HAuthorJobMenu record);
}