package com.czj.dao;

import com.czj.bean.HMoveStaff;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface HMoveStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    int insert(HMoveStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    HMoveStaff selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    List<HMoveStaff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HMoveStaff record);
}