package com.czj.dao;

import com.czj.bean.HPerformance;
import java.util.List;

public interface HPerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_performance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_performance
     *
     * @mbg.generated
     */
    int insert(HPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_performance
     *
     * @mbg.generated
     */
    HPerformance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_performance
     *
     * @mbg.generated
     */
    List<HPerformance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HPerformance record);
}