package com.czj.dao;

import com.czj.bean.HQuestion;
import java.util.List;

public interface HQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_question
     *
     * @mbg.generated
     */
    int insert(HQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_question
     *
     * @mbg.generated
     */
    HQuestion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_question
     *
     * @mbg.generated
     */
    List<HQuestion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HQuestion record);
}