package com.czj.dao;

import com.czj.bean.HStaff;
import java.util.List;

public interface HStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff
     *
     * @mbg.generated
     */
    int insert(HStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff
     *
     * @mbg.generated
     */
    HStaff selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff
     *
     * @mbg.generated
     */
    List<HStaff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HStaff record);
}