package com.czj.dao;

import com.czj.bean.HStaffIdleTime;
import java.util.List;

public interface HStaffIdleTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_idle_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_idle_time
     *
     * @mbg.generated
     */
    int insert(HStaffIdleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_idle_time
     *
     * @mbg.generated
     */
    HStaffIdleTime selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_idle_time
     *
     * @mbg.generated
     */
    List<HStaffIdleTime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_idle_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HStaffIdleTime record);
}