package com.czj.dao;

import com.czj.bean.HStaffLog;
import java.util.List;

public interface HStaffLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    int insert(HStaffLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    HStaffLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    List<HStaffLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_staff_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HStaffLog record);
}