package com.czj.dao;

import com.czj.bean.HStore;
import java.util.List;

public interface HStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store
     *
     * @mbg.generated
     */
    int insert(HStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store
     *
     * @mbg.generated
     */
    HStore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store
     *
     * @mbg.generated
     */
    List<HStore> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HStore record);
}