package com.czj.dao;

import com.czj.bean.HStoreForecastTurnover;
import java.util.List;

public interface HStoreForecastTurnoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    int insert(HStoreForecastTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    HStoreForecastTurnover selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    List<HStoreForecastTurnover> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_forecast_turnover
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HStoreForecastTurnover record);
}