package com.jie.dao;

import com.jie.bean.HDictionary;
import java.util.List;

public interface HDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    int insert(HDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    HDictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    List<HDictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HDictionary record);
}