package com.jie.dao;

import com.jie.bean.HExam;
import java.util.List;

public interface HExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    int insert(HExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    HExam selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    List<HExam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HExam record);
}