package com.jie.dao;

import com.jie.bean.HExamQuestion;
import java.util.List;

public interface HExamQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam_question
     *
     * @mbg.generated
     */
    int insert(HExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam_question
     *
     * @mbg.generated
     */
    HExamQuestion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam_question
     *
     * @mbg.generated
     */
    List<HExamQuestion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_exam_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HExamQuestion record);
}