package com.jie.dao;

import com.jie.bean.HJob;
import java.util.List;

public interface HJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_job
     *
     * @mbg.generated
     */
    int insert(HJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_job
     *
     * @mbg.generated
     */
    HJob selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_job
     *
     * @mbg.generated
     */
    List<HJob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HJob record);
}