package com.jie.dao;

import com.jie.bean.HMenu;
import java.util.List;

public interface HMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_menu
     *
     * @mbg.generated
     */
    int insert(HMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_menu
     *
     * @mbg.generated
     */
    HMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_menu
     *
     * @mbg.generated
     */
    List<HMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HMenu record);
}