package com.jie.dao;

import com.jie.bean.HMoveStaff;
import java.util.List;

public interface HMoveStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    int insert(HMoveStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    HMoveStaff selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    List<HMoveStaff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_move_staff
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HMoveStaff record);
}