package com.jie.dao;

import com.jie.bean.HNotice;
import java.util.List;

public interface HNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_notice
     *
     * @mbg.generated
     */
    int insert(HNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_notice
     *
     * @mbg.generated
     */
    HNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_notice
     *
     * @mbg.generated
     */
    List<HNotice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HNotice record);
}