package com.jie.dao;

import com.jie.bean.HStoreColor;
import java.util.List;

public interface HStoreColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_color
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_color
     *
     * @mbg.generated
     */
    int insert(HStoreColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_color
     *
     * @mbg.generated
     */
    HStoreColor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_color
     *
     * @mbg.generated
     */
    List<HStoreColor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_store_color
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HStoreColor record);
}