package com.jie.dao;

import com.jie.bean.HVariableTimeGuide;
import java.util.List;

public interface HVariableTimeGuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    int insert(HVariableTimeGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    HVariableTimeGuide selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    List<HVariableTimeGuide> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HVariableTimeGuide record);
}