package com.jie.bean;

import java.io.Serializable;

public class HVariableTimeGuide implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_variable_time_guide.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_variable_time_guide.store_id
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_variable_time_guide.h_money
     *
     * @mbg.generated
     */
    private Integer hMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_variable_time_guide.l_money
     *
     * @mbg.generated
     */
    private Integer lMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_variable_time_guide.work_num
     *
     * @mbg.generated
     */
    private String workNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_variable_time_guide.id
     *
     * @return the value of h_variable_time_guide.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_variable_time_guide.id
     *
     * @param id the value for h_variable_time_guide.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_variable_time_guide.store_id
     *
     * @return the value of h_variable_time_guide.store_id
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_variable_time_guide.store_id
     *
     * @param storeId the value for h_variable_time_guide.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_variable_time_guide.h_money
     *
     * @return the value of h_variable_time_guide.h_money
     *
     * @mbg.generated
     */
    public Integer gethMoney() {
        return hMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_variable_time_guide.h_money
     *
     * @param hMoney the value for h_variable_time_guide.h_money
     *
     * @mbg.generated
     */
    public void sethMoney(Integer hMoney) {
        this.hMoney = hMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_variable_time_guide.l_money
     *
     * @return the value of h_variable_time_guide.l_money
     *
     * @mbg.generated
     */
    public Integer getlMoney() {
        return lMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_variable_time_guide.l_money
     *
     * @param lMoney the value for h_variable_time_guide.l_money
     *
     * @mbg.generated
     */
    public void setlMoney(Integer lMoney) {
        this.lMoney = lMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_variable_time_guide.work_num
     *
     * @return the value of h_variable_time_guide.work_num
     *
     * @mbg.generated
     */
    public String getWorkNum() {
        return workNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_variable_time_guide.work_num
     *
     * @param workNum the value for h_variable_time_guide.work_num
     *
     * @mbg.generated
     */
    public void setWorkNum(String workNum) {
        this.workNum = workNum == null ? null : workNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_variable_time_guide
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeId=").append(storeId);
        sb.append(", hMoney=").append(hMoney);
        sb.append(", lMoney=").append(lMoney);
        sb.append(", workNum=").append(workNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}